### ISSUE TITLE
Table Component

### ISSUE THREAD

**Issue by fadwamahmoud** [librocco/librocco#113]
Using [svelte-headless-table](https://svelte-headless-table.bryanmylee.com/#headless) lib we could build one component for the table

### Props:

data (`TableData[]`) : 
Array of data needed to create a Svelte store to present on the [Table](https://svelte-headless-table.bryanmylee.com/docs/api/create-table#usage)
Type would be the same as books schema, which I implemented as the following until we finalize a schema

`type TableData = {
	ISBN: number;
	Titulo: string;
	Autore: string;
};
`

### Styles:

Header : similar to this [component](https://tailwindui.com/components/application-ui/lists/tables#component-7b5a46e74e475708d966ca31716f1771) on tailwindUI for the sorting functionality

Row: checkbox rows like [this](https://tailwindui.com/components/application-ui/lists/tables#component-390db22a862687fe88b313692989ffaf)

### Functionality:

Sorting for all columns
Select functionality TBD

### Enhancements

[Stacked](https://tailwindui.com/components/application-ui/lists/tables#component-e56f750c63d4e53a24f5f0bf9fd7b52a) columns for mobile view

**Comment by delasous** [comment]
Adding important considerations / notes here from #54:

1. A standard table row in the existing app consists of:
    a. ISBN - string
    b. Title - string
    c. Author - string
    d. Editor - string
    e. Quantity - number (currency format - 35.20)
    f. Price - number
    g. Year - number
    h. Out of Print - boolean
    i. Edited By - string (Future: link to user?)
    j. Classification - string (select from limited options?)
2. On the Warehouse view tables (only?) we will likely need an additional "edit" cell which opens the [Add Book / Crea Nuovo Libro popover](https://www.figma.com/file/aKxt2b7lVOivTZ5jgrQwe2/Librocco?node-id=1574%3A29713) to allow book data to be edited.
3. On the Out Note view tables will also likely need to add a special "warehouse select" cell for cases where the book could be removed from one of several warehouses. This dropdown should be prioritized on the left side of the table, as its validation errors will stop the note from being committed.

**Comment by fadwamahmoud** [comment]
Changing up this component to be more "dumb" and have its functionality controllable from the outside (in the page component), like the sidebar component.

Also first pass would be an opinionated component just for the stock page as mentioned on #123. Then we could make it more generic as we go.

### Elements:

1. `Table` : takes in children/rows
2. `TableRow`

### Functionality:

This will be implemented using plain HTML since the sorting would be on backend side, there's no point using headless-table lib.

**Comment by ikusteu** [comment]
Dead on, I would just like to elaborate a bit more. `Table` would take no props, while each `TableRow` would take the props described by @delasous ☝️ 

Maybe name the table `InventoryTable` and `InventoryTableRow`

**Comment by delasous** [comment]
Realise I'm sliding in a little late here as there's already an open PR... apologies. I had been thinking post- AttendanceVariance table that a few of the challenges I faced there with overflow/scroll might be overcome by using `grid` layout.

**Comment by delasous** [comment]
Added in #125
