### ISSUE TITLE
Feature: EditBookForm

### ISSUE THREAD

**Issue by fadwamahmoud** [librocco/librocco#117]
### Implementation:

ISBN: text field 
Titolo: text field 
Autore: text field 
A cura di: text field
Prezzo Finale: text field with start and end adornment
Anno: date
Editore: Dropdown (get options as a prop)
FC: checkbox (?)
Riassunto: text area

### Unknowns

which fields are required?
what validations are needed?

**Comment by delasous** [comment]
## EditBookForm

### Description
A basic form to add/edit a single books details. The component should accept BookData as a prop to allow an existing book to be edited. It should also validate the form control fields and provide them with error/touched props.

This form will currently be passed to #116 as a "Crea nuovo libro" tab panel, but should be usable in any other page/component within the app.

**Mocks**:
 - [Default](https://www.figma.com/file/aKxt2b7lVOivTZ5jgrQwe2/Librocco?node-id=1574%3A29713). Note: this mock is not up to date: the form control elements that that we have built have their labels on top - the elements should be composed in the same vertical order without the dividing lines and, where appropriate, lifted next to each other on bigger screens.

### Implementation Details:
1. The following form control elements should be managed by the form and built from existing FormField elements:
    1. ISBN: TextField
    2. Titolo: TextField
    3. Autore: TextField
    4. A cura di: TextField
    5. Prezzo Finale: TextField w/ "€" start adornment
    6. Anno: TextField
    7. Editore: Dropdown
    8. FC: Checkbox
    9. Riassunto: Textarea
2. Props:
    1. `BookData` - optional facts for a single book
    2. `onSubmit` - required on submit handler
    3. `onCancel` - optional on cancel handler

- "Confirm" / onSubmit button should be of `type="submit"`

**Unknowns / Todos**
1. Form state management:
  - [ ] [svelte-use-form](https://github.com/noahsalvi/svelte-use-form) seems promising. Read their docs and describe integration.
  - [ ] FormFields need to be updated to accept minimally "value" and "error" (and "touched"?)
2. Form Controls:
    - [ ] What is "FC"? Checkbox's allow a support description, can we provide?
    - [ ] "Editore" list of options?
    - [ ] Validation: Anno - year string?; Riassunto - char limit?; Which are required?

### Stories / Tests
1. Default story
2. onSubmit:
    1. Handler should be fire on click of "Confirm" button
    2. Validation errors should prevent submission of form and display expected error message next to form control

### Enhancements
1. "Prezzo Finale" form control: We need a special NumberField which controls its formatting.
3. Form control labels and errors should be internationalized. 
5. Svelte encourages building forms with "progressive enhancement", this means validation and submission should be possible without JS. I feel like this speaks to the "offline-first" aims of this app. What enhancements can we make to enable this?
