### ISSUE TITLE
Feature: Histoire enhancements

### ISSUE THREAD

**Issue by delasous** [librocco/librocco#131]
- [ ] Write up team notes on using Histoire  (docs are a scattershot) / configure. Small things to standardise, e.g default settings seem to be a single story which (slowly) loads an iframe each time the story is selected, making it painful to skim through stories. Specifying grid layout seems to fix this. Instead of specifying on a per-story basis, define this in `histoire.config.js`
- [ ] Add CI job to deploy story preview snapshot on push
    1. Use Eisbuk GCP storage bucket and Rclone
- [ ] Investigate options and (re-)setup visual regression testing. Histoire docs-examples point to either using a service called Percy or a snapshot-plugin/Cypress combo.
    1. [Percy or Plugin Screenshot](https://histoire.dev/guide/plugins/official.html#official-plugins)
    2. Github examples (sveltekit one I think) provides setup with Cypress

**Optional**:
- [ ] Investigate plugin environment:
   1. Stories do not leverage controls - is there anywhere this adds value?
   2. Ivans comment: It would be nice to get some JSDoc parser: showing props in docs, storybook had it and I believe that might have been causing an issue with pnpm (some dependency of a dependency of that package 😆 ).
       1. Could also use `md` files for fleshing out component docs

**Comment by ikusteu** [comment]
> Write up team notes on using Histoire (docs are a scattershot) / configure. Small things to standardise, e.g default settings seem to be a single story which (slowly) loads an iframe each time the story is selected, making it painful to skim through stories. Specifying grid layout seems to fix this. Instead of specifying on a per-story basis, define this in histoire.config.js

I have one problem with this and that is the `InventoryPage` (for instance), where an entire page view is displayed as prototype and it doesn't make too much sense IMO to make them grid displayed.

The solution might be to remove the story altogether, maybe even move the `IntervalPage` to `/apps/web-cliebnt` (as it's not an atom) and then use a different form of visual regression testing (with cypress/playwright) for pages (and not histoire). 

Let me know your thoughts.
