### ISSUE TITLE
Order notes latest-first

### ISSUE THREAD

**Issue by ikusteu** [librocco/librocco#178]
The note ids are timestamped (with lexicographically comparable strings), so the notes themselves are sorted oldest first in the db. 

I believe the desired behaviour is the opposite and that we would like our notes (in side nav) to be sorted latest-first:
- outbound notes should be sorted latest first
- inbound notes should be organised per warehouse basis (warehouses sorted lexicographically, `0-all` first), but the notes inside each warehouse should be sorted latest-first

This should probably be implemented on db side (in the design document if possible). If not possible, or hard on performance, maybe it would make sense to do it client side (but I doubt it).

**Comment by ikusteu** [comment]
This might not be necessary if we're showing only the non-committed notes...I don't imagine there being many of those floating around at the single time. @silviot what do you think?

**Comment by ikusteu** [comment]
@silviot can I get your thoughts on this? ☝️ Seems stale/unnecessary...

**Comment by ikusteu** [comment]
@silviot is this still relevant, considering we're not displaying the committed notes, so I don't imagine there being a large number of notes open at the same time

**Comment by silviot** [comment]
@ikusteu I agree, we can close this (at least for now - we might revisit this).
