### ISSUE TITLE
Create page for entering remoteDB

### ISSUE THREAD

**Issue by fadwamahmoud** [librocco/librocco#212]
A settings page similar to the debug page, with an input element that takes in the remote db url and stores it in local storage

**Comment by delasous** [comment]
Proposed actions:
1. Add a new route-page: `/settings/+page.svelte` for managing app-user settings
2. Add form to page with single input for managing remote db url (`http://${COUCHDB_USER}:${COUCHDB_PASSWORD}@${COUCHDB_HOST}:${COUCHDB_PORT}/${DB_NAME}`):
    1. We could also break url apart into individual fields (user, password, host, port, db_name), which means application can manage format of string?
    2. Form should save remote config to local storage
    3. Page should load remote config into form from local storage if it exists
3. `/inventory/+layout.svelte`:
    1. In Dev:
        1. Continue to run replication when app is started, and remote config is static to our local couch container => read config from env
    2. In production: 
        1. We should only run replication if the remote config is defined in local storage
        2. Remote config shouldn't be static => don't read it from env
        3. When remote config is saved via settings form, we should trigger replication
4. UX / communication:
    1. Because replication might take a few mins, we should indicate this to user on remote config form before they save it
    2. I think we should also use a different term for it in UI. The longer I stared at "Replicating..." the less I felt like non-technical users would have a clue what they were waiting for. Juries out on this still - I will ask Quipster to throw a few suggestions at the wall.
    3. It could also be fun to display [a random quote](https://github.com/lukePeavey/quotable) for every 30 seconds/ min that the replication is loading? It is already fetching a load of book data.
    4. Notifications:
        1. User defined remote config could be incorrect, and replication could fail as a result => we should provide an error toast if something goes wrong and return them to settings page to retry
        2. Saving settings form / writing to local storage should provide a success toast

**Comment by fadwamahmoud** [comment]
Looks great to me! I think having multiple fields for the url would make it a lot more user friendly. Also maybe a more familiar term for Replicating could be "Syncing"?  @delasous
