### ISSUE TITLE
Hash based routing

### ISSUE THREAD

**Issue by fadwamahmoud** [librocco/librocco#229]
Replace sveltekit's filesystem based routing with hash based routing:

Tasks:

- [ ] Create routes file with direct routes, routes including parameters, and wildcards to catch the rest of the routes.

libroc.co/base/#/

    - /inventory
        - inbound/:versionedNoteId?
        - outbound/:versionedNoteId? 
        - stock:/versionedWarehouseId? => falls back to v1/0-all
    - /debug
    - /settings 
    - /* fallback page

- [ ] Give unique url to each item on page
- [ ] Set page state based on URL

**Comment by fadwamahmoud** [comment]
Would you guys mind taking a look? @silviot @ikusteu @delasous

**Comment by fadwamahmoud** [comment]
In a nutshell, svelte-spa-router cannot be used because it goes against sveltekit and its default behaviour.  

It's [not designed to work with sveltekit](https://stackoverflow.com/questions/70529698/svelte-spa-router-invalid-component-object-error) which I've realised after having tried the following:
- I couldn't leverage +layout which means I have to implement its behaviour manually by creating nested routes inside inventory, where inventory renders the layout and then inbound, outbound, stock are nested.
- Sveltekit wouldn't recognize the corresponding load function so I have to import it and re-export it from the component's  module context  which is a bit less clean.
- I wasn't able to use imported `Router` object from svelte-spa-router because I was getting this error `Invalid component object` which led me to the stackoverflow answer above and confirmed my thoughts.

So instead I'll implement it manually by setting the page data/state using the url and listening to hashChange and popState events. I'll write up the edited tasks in this ticket.

**Comment by silviot** [comment]
Related: https://github.com/sveltejs/kit/issues/7443

**Comment by delasous** [comment]
Closing this for now given that deployment now works with #230.
