### ISSUE TITLE
Feature:  Pagination (NumberLinks)

### ISSUE THREAD

**Issue by ikusteu** [librocco/librocco#23]
## Component: Pagination

**Description:** A navbar with numbers for links (used for some sort of pagination). The first pass should be stateless (both `onButtonClick` and `currentItem` should be passed as props). As an enhancement, we can add a component wrapping the stateless one with React router (route matching and `Link` as element `Wrapper`). Implements #40, but no need for separate component as the #40 is defined with a simple set of classNames and trivial button functionality.

**Mockup:** [Figma](https://www.figma.com/file/yjspFXBKBIFJlC3wFv1FJL/The-Brocco?node-id=20%3A2337)

#### Props:

- maxItems (optional: number):
  - default: 7
  - I think the minimum should be 5, as 3 would just show the current and the dots
  - should probably fall down to previous odd number in case an even number has been provided
- links (required: Array<string>):
  - if none provided - component is not rendered
- wrapper (optional: React component):
  - to be used to possibly wrap each element with react router Link (or such)
  - should be able to accept `to`, `disabled` (as those props will be passed from the component to each wrapping element, according to internal state)
- onButtonClick (optional: Function):
  - should accept `linkTo: string` and `i: number` (0 - based index of clicked button/link)
- className (optional: string):
  - shouldn't override anything from the core component (enhancement: only accept positioning)
- currentItem (number):
  - index (0 - based) of currently selected item

#### Storybook (stories):

- Default
- Try out different combinations with different `...` positions as that functionality might be a bit tricky

#### Functionality (should be tested):

- rendering:
  - should respect the `maxItems` prop while rendering
  - should display odd number of items (fall back to `maxItems - 1` if the odd number was provided)
  - should throw on `maxItems < 5`
  - should hide the correct links behind `...` (if more than `maxItems` provided)
- onChange:
  - should call the `onChange` function with the right value for `url` on link click
  - should call the `onChange` function with the right value for `url` on next/previous button click
- wrapper:
  - should wrap the element and pass the right values for `disabled` and `to`

### Possible enhancements:

- create a helper to filter all non position-related Tailwind classes
- create a `PaginationLinks` component wrapping `Pagination` into react router logic

**Comment by delasous** [comment]
Looks good to me. Without knowing much about the how-tos / best-practises around implementing pagination, its hard to make more concrete recommendations... I will have to do some reading.

Some thoughts from [PageLink](https://github.com/librocco/librocco/issues/40) that I think are relevant here: 
- Each link could be passed an `href`/`pathname` with a relative query string that defines the pagination parameters. This container could define those.
- The ellipsis functionality is a little tricky, especially the way it is currently mocked as a middle point between two Page Ranges. I agree with your suggestion that `maxItems` should be 5. Instead of being wedged between two ranges, the ellipsis could potentially just move the Page Range forward and back by increments of 5, like so:
  - 6 pages = [1, 2, 3, 4, 5, ...] => [..., 6]
  - 13 pages = [1, 2, 3, 4, 5, ...] => [...,  6, 7, 8, 9, 10, ...] => [..., 11, 12, 13]
Its action would be a little different than the Number or Arrow variant of PageLink: it should move the Page "forward" or "back" to the lowest or highest Page in the new range (e.g clicking "..." after 5, moves to 6; clicking "..." before 11, moves to 10), but should also potentially update the definition of the current range. These parameters could be handled through a query string?

If no links are provided, i.e there are no Pages because all of the results < the page size default (10, 20, 30?), this container should not be rendered.

**Comment by ikusteu** [comment]
Oh and the idea was for the elipsis (if by that you mean the `...`) is not to be clickable.

**Comment by ikusteu** [comment]
I like the idea of paginating by "range" (the way you've imagined it), but I don't think we need to go too fancy here as it will (currently) be used to paginate through search results, which can alway be narrowed down, using search string, rather than clicking through, and if you want to click through (meaning - you're looking for something, but can't pin point it exactly), you would just use the '<' '>' arrows and skim over each element.

**Comment by ikusteu** [comment]
As for the links: I've mentioned that in the spec (under props) as `links` props. I think `string` will suffice (as each link, be it absolute or relative). And then each change would either:
- be handled through `onChange` - at which point the `onChange` will be called with current link (pathname), e.g. `onChange("page-7")`
- be handled through React router's `Link` component in a way that when each element is rendered, it could pass the current `link` (current member of `links` prop, when mapping through) as `to`. If the former `onChange` logic is used, this can be omitted, but if we use this, the `Wrapper` prop should then be `Link` (which acepts `to` and `disabled` as props and each href will automatically be passed as `to` to corresponding Link element)

**Comment by ikusteu** [comment]
Anyhoo, without writing too much here, I've already implemented a lot of that functionality yesterday, and we can go over it during (or after) the meeting

**Comment by delasous** [comment]
Your comments make complete sense! Simplifies it drastically if `...` is not clickable, and your description of both strategies for the 'linking' is clear. I think it is worth continuing down the path you have already started!

**Comment by ikusteu** [comment]
The naming: I'm not too happy with `PageLinkContainer` for two (semantic) reasons:
1. Most links link to a page, so you see the possible confusion there
2. As this would be developed as a whole (call it an atom or a molecule), it shouldn't be named container. Containers hold some (arbitrary) content while this component will always render the same content. I like the `NumberLinks` better, but that implies links (which might or might not be used here), so we can call it `PaginationNav`, or simply `Pagination`.

**Comment by ikusteu** [comment]
Oh and sorry, to respond to your comment: Yeah, it does simplify it a great deal, but we can always add the range pagination as an enhancement, but we can talk about that when and if necessary as it would provide a lot of edge cases (I don't know if your familiar with the eisbuk date nav and paginating weeks, months, days, switching back and forth between `jump` length, etc.)

**Comment by ikusteu** [comment]
**Edit:** remove `as` (should always be `nav`)
**Edit:** `onChange` -> `onButtonClick`
**Edit:** add `currentItem`prop

**Comment by delasous** [comment]
I agree with your thinking on name change. 

I had a brief look at the Eisbuk date nav once, then backed away from it very slowly. I think its sensible to keep it simpler here

**Comment by ikusteu** [comment]
> (...) then backed away from it very slowly.

😂

**Comment by delasous** [comment]
Closed with #60
