### ISSUE TITLE
Feature: Scan input enhancements

### ISSUE THREAD

**Issue by delasous** [librocco/librocco#235]
- [ ] Figure out how to configure and add an event listener for a scanner to pass an ISBN to the input and submit it 
    - (Have no clue how this would work - is it a universal?)
    - Should communicate success via "book added" toast; should communicate failure via error help text on input
- [ ] Fix: a random ISBN string will add a book row with undefined values. It should not add a row, and should communicate via help text on input that the book is not found

**Comment by ikusteu** [comment]
First point is fixed in #335 
Second point is not the desired behaviour
