### ISSUE TITLE
Feature: PWA

### ISSUE THREAD

**Issue by fadwamahmoud** [librocco/librocco#239]
I have already worked on setting up vite-pwa/sveltekit which now: 

- Generates a service worker 
- Generates a web manifest
- Registers the sw
- Links the manifest

However the app is still not installable

Requirements:

- [ ] Fix the "no matching service worker detected" warning message that shows up in the manifest which would most likely solve this

https://test.libroc.co/feature/sveltekit-pwa-plugin/inventory/stock/0-all/

**Comment by ikusteu** [comment]
@fadwamahmoud was this fixed? (I know there's some PWA in the code, in `main`)

**Comment by fadwamahmoud** [comment]
@ikusteu not as far as I remember
