### ISSUE TITLE
Feature: CardFooter

### ISSUE THREAD

**Issue by ikusteu** [librocco/librocco#24]
## Component: CardFooter

**Description:** To me this looks like a purely presentational (container) component: rendering something to the left and right section and maybe wrap those sections to display one under the other in mobile.

**Mockup:** [Figma](https://www.figma.com/file/yjspFXBKBIFJlC3wFv1FJL/The-Brocco?node-id=17%3A4748)

#### Props:

- leftSection (optional: JSX.Element)
- rightSection (ooptional: JSX.Element)

#### Storybook (stories):

- Default
- Empty Variants (only left and only right provided maybe...)

#### Functionality (should be tested):

- null

### Possible enhancements:

- null

**Comment by delasous** [comment]
Looks good to me!

**Comment by ikusteu** [comment]
Closing this as it's covered in #67
