### ISSUE TITLE
Feature: Wire up bookDetailForm slideover

### ISSUE THREAD

**Issue by fadwamahmoud** [librocco/librocco#242]
The bookDetailsForm component needs to be wired into the create button on transactions table as a slideover. Book details could be provided on create and are editable.

- [x] SlideOver
- Add slideOver slot to InventoryPage component

- [x] Edit Button
- Add Edit button to transaction row inside inventoryTable component 
- Edit button in InventoryTable component should trigger slideOver 

- [x] Create functionality
- empty local State
- isbn field is enabled
- internally triggers bookInterface.upsert() then note.addVolumes()

- [x] Edit functionality
- local state of the currently edited book
- isbn field is disabled
- internally triggers bookInterface.upsert() 

- [x] Misc
- book form sizing (shorter than slideover)
- remove asterisk from ISBN field when disabled?
- Change title based on create vs edit  

### Potential enhancements:

- Include quantity in the form and get rid of handleQuantityChange (haven't thought this through yet)
- Validation for trying to add an existing isbn

**Comment by delasous** [comment]
@silviot to confirm: should the user be able to edit the details of a bookEntry on inbound and outbound tables? Or is this something that is only possible directly on the Stock table?

**Comment by delasous** [comment]
Slideover should also be opened from ["Create" button in ISBN search field](https://www.figma.com/file/aKxt2b7lVOivTZ5jgrQwe2/Librocco?type=design&node-id=2291-35074&t=GkjwEmMmFlmHM9G5-0) for "create functionality"
