### ISSUE TITLE
Build `publisherList` from the current database

### ISSUE THREAD

**Issue by silviot** [librocco/librocco#269]
Currently we hardcode a list of publishers in our code to drive the autocompletion in the create/edit book form. We should instead populate it from the publishers in the current database. It will start off as an empty list.

**Comment by ikusteu** [comment]
I would build on top of this and say we need to enable adding publishers first (as current select element doesn't only autofill, but doesn't typing something that's not in the list)

Tasks I see here:
- [ ] Update publisher selection field to serve as autofill, not an exclusive selection
- [ ] Create db logic (design document or a query stream) used to retrieve the available publishers
- [ ] Update book form to accept publishers as a prop + load publishers from the db and pass them to the book form (from the page component, when opening the form)

**Comment by ikusteu** [comment]
Fixed in #328
