### ISSUE TITLE
Book data extension script

### ISSUE THREAD

**Issue by fadwamahmoud** [librocco/librocco#279]
- [x] Add book resources
      annas archive
      libreriauniversitaria.it
      openlibrary
      ...TBD
- [x] Create a handler for each resource that extracts book meta data from each of these resources' html
- [x] Write an interface for the returned book data
- [x] receive isbn as a message from the app

https://github.com/librocco/bookdata-extension

**Comment by ikusteu** [comment]
This is more-less done and in a separate repo, closing
