### ISSUE TITLE
Wire in book meta data package

### ISSUE THREAD

**Issue by fadwamahmoud** [librocco/librocco#303]
### Behaviour

on isbn field blur

form is autofilled with the first of the returned results

all the other results are shown in a dropdown for each field 

### Implementation

1. check cached isbns 
2. call getbook exposed function on isbn field blur (throttle)
3. store suggestions in local state (cache in local storage?)
4. on create mode: make fields a dropdown

**Comment by ikusteu** [comment]
Stale
