### ISSUE TITLE
Plugin system for book data plugins

### ISSUE THREAD

**Issue by fadwamahmoud** [librocco/librocco#311]
- Create an interface which plugins must implement
```
 interface MyPlugin {
  initialize(): void;
  getBook(): Promise<BookMetadata>;
  cleanup(): void;
}
```
- ~~Create a class for each plugin that implements `MyPlugin`~~
- Create a way to manage the plugins like load, unload and call `getBook`. It will also manage the state of the list of plugins. 

When we decide where exactly in the data flow to fetch the book meta data, it'll be used like so:

```
const pluginManager = new PluginManager();
pluginManager.loadPlugin(new annasArchive());
pluginManager.loadPlugin(new openLibrary());
pluginManager.getBook('132414142432');
```

**Comment by ikusteu** [comment]
Closing this as it's been (and being) discussed in #323 with new tickets opened on the matter:
- #340 
- #339 
- #342
