### ISSUE TITLE
Feature: SideNav Container

### ISSUE THREAD

**Issue by delasous** [librocco/librocco#32]
## Component: SideNav Container

**Description**: 
- Vertical column container that renders a list of SideNav Links which should be aligned to the top of the container.
- Should link to:
  - Warehouse Stock page
  - IN Note page
  - OUT Note page
  - Warehouse Manage page
- Should be rendered inside the AppShell to persist between pages
- Should use Already developed `SideNavButton`'s (probably as `SideNavLink`)

**Mockup**: [Figma](https://www.figma.com/file/yjspFXBKBIFJlC3wFv1FJL/The-Brocco?node-id=13%3A4083)

### Requirements

**Props**:
- Links: An array of href/pathnames that will be rendered as SideNav Links

**Styles**:
- On small screens this container should be hidden in favour of a MobileMenu (which is collapsable from top UtilityBar)

**Storybook**:
- Default 

**Functionality (should be tested):**

Null

**Possible Enhancements**
Null

**Comment by ikusteu** [comment]
LGTM

**Comment by ikusteu** [comment]
**Edit:** Functionality

**Comment by ikusteu** [comment]
**Update**: Each "link" should contain `href` and `Icon`

**Comment by ikusteu** [comment]
**Final edit:** Revert to original, as new tickets have been opened

**Comment by ikusteu** [comment]
Closing this as new ticket has been created to represent a (grouped) unit of work and leave this as (an explanation) in it's original state
