### ISSUE TITLE
Fix CI caching

### ISSUE THREAD

**Issue by ikusteu** [librocco/librocco#331]
This is a small, but annoying one. every now and then a bunch of CI checks fail due to some "faulty packages". Each time I perform all of the checks locally, see that they are passing and then remember to bump cache versions (we're at `v5` at this point) which makes the CI pass all fine.

We should look into what's causing this and fix it.

**Comment by silviot** [comment]
Some time has passed, and now you [can click on the UI](https://github.com/librocco/librocco/actions/caches) to remove the caches. Still annoying when they get corrupted, but it's easier to reset them.
