### ISSUE TITLE
Feature: SideNav Link

### ISSUE THREAD

**Issue by delasous** [librocco/librocco#34]
## Component: SideNav Link
**Description**:
- Main navigation link to a new page to be rendered inside of the [SideNav Container](https://github.com/librocco/librocco/issues/32)

**Mockup**: [Figma](https://www.figma.com/file/yjspFXBKBIFJlC3wFv1FJL/The-Brocco?node-id=13%3A4070)

### Requirements
**Props:**
- Selected: A boolean flag to indicate Inactive/Selected state
- as: (optional: keyof JSX.IntrinsicElements): default => a

**Styles:**
- Inactive (Resting) ⇒ No background (falls through to SideNav Container background); gray text
- Selected ⇒ Gray background; white text; hover pseudo text-white

**Storybook:**
- Variants:
  - Inactive
  - Selected

**Functionality**
- Click on Inactive Link should route to `href`/`pathname` specified by icon
- Click on Selected Link should do nothing  

**Possible Enhancements**
Null

**Comment by delasous** [comment]
Going for 100% completion here... but also wanted to suggest the following updates:

In description of [SideNav Container](https://github.com/librocco/librocco/issues/32) I suggested it should accept an array of `href`/`pathname`s. This would mean that SideNav Button should become SideNav Link:
- The default `as` htmlTag becomes an <a>, or a react router <Link> (this will only be local navigation)
- It accepts an `href`/`pathname` prop: A string to route to when clicked.
    - Or alternative this could alternately be handled in onClick handler that is passed in from SideNav Container

Thoughts?

**Comment by ikusteu** [comment]
These are both overly simplified examples and I might be wrong about the `to` prop (former `react-router-dom` versions used it, but they might have changed it)

**Comment by ikusteu** [comment]
Also, if we go with the latter (which I think we're leaning towards), the `ui/SideNavButton` can be removed and the `SideNavLink.tsx` be kept inside of `SideNavContainer` (which would then be renamed to simply `SideNav`)

**Comment by ikusteu** [comment]
Closing this as it's been included in #61

**Comment by delasous** [comment]
> Also, if we go with the latter (which I think we're leaning towards), the `ui/SideNavButton` can be removed and the `SideNavLink.tsx` (and the stories) be kept inside of `SideNavContainer` (which would then be renamed to simply `SideNav`)

I agree with this approach
