### ISSUE TITLE
Feature: TableHeading

### ISSUE THREAD

**Issue by delasous** [librocco/librocco#35]
##Component: TableTitle
**Description**: 
- A heading which sits above the BookTable in the main area of the app shell.
- Consists of two parts (which can potentially be broken down into smaller atoms?):
  1. The Title
  2. The Subtitle
- Can be rendered in two contexts:
  1. Warehouse Stock page, where:
    a. Title = Warehouse Name ("Nuovo 2022") and is not editable; 
    b. Subtitle is not present;
  3. IN/OUT Note page, where:
    a. Title = Note Name ("<Author>" or "<Date>"). In this context: Title should be set to an agreed default when a new note is created, and can be edited here-inline*. Editing should propagate name change to NoteFileNav.
    b. Subtitle = "in <Warehouse Name>"

* Note: Mock currently doesn't reflect ability to edit. Silvio has suggested a small inline pencil icon (to the left?) the when clicked changes text element to input element.

**Mockup**: [Figma](https://www.figma.com/file/yjspFXBKBIFJlC3wFv1FJL/The-Brocco?node-id=109%3A3066)

### Requirements
**Props**:
- Title: A string name for the Warehouse or Note
- isEditable: A boolean that allows Title editing
- Subtitle: If Note Title, a string name for its Warehouse, prepended by "in"

**Styles**:

**Storybook**:
Variants:
- Static (Warehouse Title)
- Editble (Note Title)

**Functionality**
- Pencil icon inline of Title should toggle text element to input element (and carry text as current value). Clicking pencil icon again, or pressing enter should update current Note name (propagating change to NoteFileNav column on left), and should switch back to text element.

**Possible Enhancements**
Null

**Comment by delasous** [comment]
After writing this: I think the editable title and its pencil icon should be broken down into its own atom, called TableTitle.

**Comment by ikusteu** [comment]
This is an ok spec, when talking about the specific component, but I would break this down into two more generic components:
1. `Typography` - It would be cool if you could group all of the typography used and then we can create a component accepting variant (heading, subheading, text, or any other way that makes sense according to the mockup) and size. This would then be used across the entire app for all texts (not necessarily for button text, but you get my point)
2. `EditableTypography` - here we can put the wysiwyg logic (plus the pencil icon) and it can extend `Typography` -> when in non-editing view it would be simple `Typography` component (with variant, size, etc. passed down) and when editing mode it would show the input element of the appropriate size.

**Comment by ikusteu** [comment]
Right...so after examining this further, to me it makes sense to divide this into multiple tickets, some more generic, and some downright opinionated.

The more generic ones (as I've mentioned above), would be atoms and reusable across the app:
- Typography
- FormField
- TypographyEditable: would wrap the former two in wysiwyg logic, add the pencil button (and render one or the other) 

The opinionated ones (those feel more like organisms) would include the title/subtitle, wouldn't need the `isEditable` as two components (more like views) would be two different contexts with their logic natively set on using either `Typography` or `TypographyEditable`. Those would be (as you've mentioned above): 
- Warehouse stock page
- In/Out Note page

**Comment by ikusteu** [comment]
Closing this as new tickets have been open to address the features mentioned here. @delasous please chime in as most of those need some more massaging:
- #62 
- #63 
- #64 
- #65 
- #66

**Comment by delasous** [comment]
Really like your approach here! Particularly `Typography` as a way to reuse standard H and P styling throughout app. I will prepare this in mock.
