### ISSUE TITLE
Fix: empty book row quantity 

### ISSUE THREAD

**Issue by delasous** [librocco/librocco#358]
1. A book rows quantity input will not allow me to enter 0 or decrease from 1 to 0, but it can remain empty
2. If I commit a note with that empty value then checkout the Stock page, I will see NaN as the quantity for that row
    1. This will happen if the book did not previously exist in that warehouse, and will also happen if it did exist (e.g quantity for that row could go from 10 to NaN)
3. Besides validating this, should we consider selecting the row for deletion if the user drops the value to zero? This could be the same interaction as clicking the rows checkbox, and the "Delete X" button appearing in the table header.

**Comment by ikusteu** [comment]
I wouldn't really consider this for deletion, it seems weird UX-wise IMO. 

Also, I don't think not being able to set the quantity to 0 is a bug (I've actually made it so intentionally). Allowing for empty value definitely **is** a bug, but should also be a quick fix. 

Finally, as for stock page, we could (and probably should) add an additional check and ignore `NaN` quantities when calculating stock (as for 0-quantity stock entries - they won't be displayed)
