### ISSUE TITLE
Feature: TopBar (UtilityContainer)

### ISSUE THREAD

**Issue by delasous** [librocco/librocco#36]
## Component: TopBar

**Description:**
 - Horizontal container on top bar of app which houses:
   - App logo
   - Search input
   - New OUT Note button ("quick draw" available anywhere in App)
   - (Mobile only) Menu Toggle "burger"

**Mockup**: [Figma](https://www.figma.com/file/yjspFXBKBIFJlC3wFv1FJL/The-Brocco?node-id=17%3A4443)

### Requirements:

I feel like it makes sense to control the rendering of search bar with respect to `onSearch` prop being present, without it the search is useless (and I'm a little unclear as to whether the search will be used in all views and how) @delasous please chime in here.
Additionally, I think the same logic can be applied to the top right button: It would be rendered with respect to `buttonProps` (if provided)

#### Elements:
- Logo:
  - passed through props as an SVGComponent
- Search bar: 
  - specified in #38, no need for separate component
- New note button:
  - component: #46 
  - rendered using `buttonProps`
  - will it be used for new IN/OUT note or just one of the two is TBD (@delasous please chime in here)
- Menu Toggle "burger" (Mobile only) - Position TBD, @delasous please chime in here

#### Props:
- **Logo** (required: SVGComponent)
- **onSearch** (optional: Function):
  - should be called with search string as a parameter
  - the suggestion is that the search field is not shown in absence of `onSearch` 
- **buttonProps**: TBD when #46 is merged in

#### Styles:
- mobile view: TBD

#### Storybook:
- Desktop
- Mobile (might be hard to achieve, but the ~~`storybook-addon-pseudo-states` might be helpful here~~ -> **update:** screen size is not a pseudo state, therefore can't be controlled using aforementioned add-on, but [storybook-addon-responsive-views](https://storybook.js.org/addons/storybook-addon-responsive-views) might be the solution)

**Functionality**
- search bar
  - should call `onSearch` with the search string as a param
  - should not be rendered if no `onSearch` present
- button: 
  - might need to be wrapped in `Link` component, but that's TBD

**Possible Enhancements**
Null

**Comment by ikusteu** [comment]
**Edit**: update props, suggest `onSearch`, `buttonProps` rendering functionality. @delasous please chime in

**Comment by ikusteu** [comment]
I would call it `TopBar`, but whatever works

**Comment by ikusteu** [comment]
Renamed to `TopBar` rather than `UtilityContainer` as it will always be placed on top and doesn't "contain" any dynamic content.

**Comment by delasous** [comment]
Agree with name change and updates.

**Comment by delasous** [comment]
> and I'm a little unclear as to whether the search will be used in all views and how

I think we collectively still need to define this behaviour. Right now my view of it is that the Search is usable from any page within the app, but search results are only displayed on the Warehouse Stock Page (#65), meaning we would have to navigate to that page before displaying. I don't think this is ideal, and can see other issues with this angle. I think a better solution will come from figuring out what the user might want to do with the search results...?

**Comment by delasous** [comment]
> will it be used for new IN/OUT note or just one of the two is TBD (@delasous please chime in here)

There will only be an OUT note button here. Thinking of this as a "quickdraw" for a User to be able to immediately start withdrawing books (a line of impatient customers in front of them)

**Comment by ikusteu** [comment]
:+1:

**Comment by delasous** [comment]
Closing as the majority of this spec/discussion is stale: the Search Input and New Out Note Button will not be managed "globally" at the top of the app.
