### ISSUE TITLE
Feature: SearchTextInput

### ISSUE THREAD

**Issue by delasous** [librocco/librocco#38]
## Component: SearchTextInput

**Description:** 
- A full-width text input that will accept query for full text search of all stock in book store. 
- How this search will return results is TBD. 
- The input does not have a right border, but on smaller screens/mobile overflow should be hidden.
- Keyboard return should implicitly start search, but should we also add additional cues? Click on magnifying glass; or a "kbd" element <kbd> Enter </kbd>

**Mockup**: TODO extract from UtilityToolNav in Figma

### Requirements:
**Props:**
- Query: The string to pass to the full text search

**Styles:**
- Overflow hidden 

**Storybook**
- Default
- Long text input

**Functionality**
- Triggers full text search. TBD how it will display results.

**Possible Enhancements**
Null

**Comment by ikusteu** [comment]
> How this search will return results is TBD.

I've mentioned this in #36 and I think `onSearch` is the simplest solution and then let the app/page component take care of what it will do with it.

**Comment by ikusteu** [comment]
> The input does not have a right border, but on smaller screens/mobile overflow should be hidden.

Yeah, could you please provide the way you see it in mobile, but no need to show a separate search input in the mockup, it can be #36 as a whole

**Comment by ikusteu** [comment]
> Keyboard return should implicitly start search, but should we also add additional cues? Click on magnifying glass; or a "kbd" element `Enter`

This is a good discussion point, but I think we can move that discussion into #36

**Comment by ikusteu** [comment]
> Query: The string to pass to the full text search

This shouldn't be passed unto the component, but rather lifted from the component (using `onSearch`). Unless I'm missing something and something should be added on top of the search string.

**Comment by ikusteu** [comment]
> Triggers full text search. TBD how it will display results.

This component need not concern itself with rendering of the results. That will be done by the table component, as to where the logic will live, isn't yet defined, could be:
  - Redux (I don't favour it for this, limited, amount of global state
  - Possibly inside the page component, rendering the table as well as the results (string) and `Pagination`

**Comment by ikusteu** [comment]
Closing this as the functionality is trivial (`input` element, possibly wrapped in `form`, for on `enter` submit functionality), and the styles are very simple (typeface, no border/outline, size). Therefore, no need for it to be a separate component (just a part of #36 ). If, at some point we want to reuse the styles, we can then create a separate component.

**Comment by delasous** [comment]
Agree with your comments and decision to roll this into #36. Re: mocks for mobile - I think that will have to wait until we get Alex involved.
