### ISSUE TITLE
Feature: PageLink

### ISSUE THREAD

**Issue by delasous** [librocco/librocco#40]
## Component: PageLink
**Description:** 
- A button or link to view a new range of Page Results (of Warehouse stock)
- There are 3 variants:
  - Number: directs to a specific Page number
  - Arrow: directs one page left or right of the current Page
    - Sub Variants:
      - Left
      - Right
  - Ellipsis: updates middle point of Page Range, and directs to lowest number page in new Lower Bound (see [PageLink Container](https://github.com/librocco/librocco/issues/23) for discussion on pagination functionality. 
- Alternatively: it doesn't manage its variants, but accepts a string (number / ellipsis) or icon (left / right) child, and these are composed in PageLink Container

**Mockup**: [Figma](https://www.figma.com/file/yjspFXBKBIFJlC3wFv1FJL/The-Brocco?node-id=20%3A2292)

### Requirements:
**Props:**
- Type: String enum of variant
- `href`/`pathname`: query string that defines pagination parameters
  - or alternatively `onClick` handler passed in from PageLink Container that defines this.

**Styles:**
- Inactive (resting): 
- Current: Light purple background; medium purple border and text-colour
- Hover: ...
- Active: ...

**Storybook**
Variants outlined in description

**Functionality**
- Clicking the link should update the pagination parameters which will:
  - Update the books-rows in the current BookTable view
  - Update the Page Ranges

**Possible Enhancements**
Null

**Comment by ikusteu** [comment]
Closing this as it's a trivial button with a simple set of styles, no need for a separate component, everything is implemented in #23
