### ISSUE TITLE
Feature: PageResults

### ISSUE THREAD

**Issue by delasous** [librocco/librocco#41]
## Component: PageResults

**Description:**
- Text describing the pagination of stock in a selected warehouse or search. 
- The results indicate how many books-rows there are on the current table (a default Page Size or less) by indicating the current page range, and how many total books there are. 

**Mockup**: TODO separate mock from parent in Figma

### Requirements:
**Props:**
- Range: Number indicating the current page range - e.g "1 to 10", "11 to 20"...
- Total: Number indicating the total number of books

**Styles:**

**Storybook**
Default

**Functionality**
Null

**Possible Enhancements**
Null

**Comment by ikusteu** [comment]
No need to make this a component. It is a feature and it's good to keep this explanation, but I've merely included it in #65.
Implementation-wise, This is just a #62 component, we could only separate the function which will generate the text, but I think we'll have the i18n at some point and can format it that way.
