### ISSUE TITLE
Feature: FileNavContainer

### ISSUE THREAD

**Issue by delasous** [librocco/librocco#43]
## Component: FileNav Container
**Description:** 
- Vertical container for main-area left-column to house lists for different pages:
  - Warehouse list
  - IN Note list
  - OUT Note list
- See note in styles on considerations for small screens

**Mockup**: TODO: Standard component reference in Figma.

### Requirements:
**Props:**
- Null

**Styles:**
- Not yet considered how this space will be managed on smaller screens. One option would be to stack as horizontal container on top of table & title. This may need to be collapsable if Warehouse/Note length can be long

**Storybook**
- Default

**Functionality**
Null

**Possible Enhancements**
Null

**Comment by ikusteu** [comment]
Closing this as it's been included in #67

**Comment by ikusteu** [comment]
> Not yet considered how this space will be managed on smaller screens. One option would be to stack as horizontal container on top of table & title. This may need to be collapsable if Warehouse/Note length can be long

Yeah, this seems natural to me. I've thought about this when creating ticket #67 as that logic (abstracting container styling for page template) would make it easier to achieve this kind of styling (rearranging items on small screen). I've also thought it should be collapsable, for that case, we can extend #67 spec to maybe render different content for sm, or just have the list be a modal, overlaying the entire page, being full height of the device and scrollable in itself. If you open [this](https://www.yeapersonalize.com/) on mobile, click on hamburger and expand services section, you can get something similar to what I was going to suggest.

But let's continue this discussion in #67
