### ISSUE TITLE
Feature: ListItem

### ISSUE THREAD

**Issue by delasous** [librocco/librocco#45]
## Component:  ListItem

**Description:** 
- Lists a Warehouse or Note name.
- Should indicate the current Warehoues/Note.
- Should indicate when Warehouse/Note name is edited from TableTitle
- Should be able to accept Icon to left of label (currently only used for Warehouse List)

**Mockup**: TODO: Standard component reference in Figma. Note: For now refer to highlighted/unlighted item in [this view](https://www.figma.com/file/yjspFXBKBIFJlC3wFv1FJL/The-Brocco?node-id=101%3A4320)

#### Props (should extend `React.HTMLAttributes<HTMLButtonElement>`):
- active?:
  - boolean
  - should display styling for active, as specified in the mockup  
- lastUpdated:
  - number
  - should control the display of flash animation on note update, see **functionality** section 👇 
- Icon (optional: SVGComponent):
  - icon to be shown before the text   

#### Styles:
- Default: no background, just text
- Active: Medium purple left border
- Updated: 
  - (undecided) flash of colour
  - this flash will be shown when the **lastUpdated** prop is truthy

#### Storybook:
- Variants:
  - should include `current` and `updated` variants
  - should display button for each variant to flash (simulate update)

#### Functionality:
- `onClick`
- controlling flash animation:
  - **lastUpdated** will control the flash animation
  - the initial value should be `0`, and each time the item is updated, this value should change (this will be done outside the element)
  - `ListItem` should understand the following values for **lastUpdated**:
    - `0` - should show no animation (this should alway be the initial state), should be passed as `key` to the rendered element
    - `<non-zero-number>`: 
      - this will be controlled from outside the component
      - should be passed as `key` to trigger flash animation each time it changes
      - should add `<animation-class-tbd>` className to the rendered element

**Possible Enhancements**
Null

**Comment by ikusteu** [comment]
> On click should change main area view to current Warehouse or current Note (with BookTable)

This functionality is already described in #47 and #48, which are prefect places to describe that. I'll update this to only specify the component without it's surrounding functionality

**Comment by ikusteu** [comment]
**Edit** the props and functionality, changed "selected" to "active" (as I've used it already for `Pagination` component) and we wish to keep things consistent (naming an all)

**Comment by ikusteu** [comment]
A code snippet I've used to test my hypothesis for forcing one time animation:

**pkg/ui/tailwind.config.js**

```typescript
const theme = require("../scaffold/tailwind.theme");

module.exports = {
  content: ["./src/**/*.{ts,tsx,html}", "./index.html"],
  theme: {
    ...theme,
    extend: {
      ...theme.extend,
      animation: {
        flash: "flash 500ms linear",
      },
      keyframes: {
        flash: {
          "0%, 100%": { backgroundColor: "inherit" },
          "50%": { backgroundColor: "green" },
        },
      },
    },
  },
  plugins: [],
};
```

**Random component, I've used Button component stories**
```typescript

export const Flash = (): JSX.Element => {
  const [key, setKey] = useState(0);

  const flash = () => {
    setKey(Date.now());
  };

  return (
    <Button key={key} onClick={flash} className="animate-flash">
      Flash
    </Button>
  );
};
```
