### ISSUE TITLE
Set up storybook for `web-client` app

### ISSUE THREAD

**Issue by fadwamahmoud** [librocco/librocco#451]
Postponed. I've really wrestled with Storybook trying to set it up. It's currently failing relating to @storybook/addon-svelte-csf (it's just not working) and I'll investigate/revisit at a later date. 
Will use Histoire to move the components to the web-client and revisit later 
[T-301](https://height.app/JUbb87uPQb/T-301)

**Comment by delasous** [comment]
It is very easy to setup now, so if we start working on Order mgmt UI and feel like it would help again, I can copy setup over from Edible
