### ISSUE TITLE
I can't get an updated version of the code

### ISSUE THREAD

**Issue by fadwamahmoud** [librocco/librocco#452]
Visiting  [test.libroc.co/main/](https://test.libroc.co/main/) with my browser shows an older version of the app. No matter how much I reload, I can't get the newer one.

I suspect there's some code in the service worker that prevents refreshing content.

I also think it would be good to start using some sort of versioning, and include the current version number in the settings page.
[T-296](https://height.app/JUbb87uPQb/T-296) 

Related to: #239

**Comment by silviot** [comment]
> I suspect there's some code in the service worker that prevents refreshing content.

Yeah, I believe that's the case. It's useful to be able to load the page even if the server is unreachable. I usually update the code by holding `shift` while clicking on the `reload` button

> I also think it would be good to start using some sort of versioning, and include the current version number in the settings page.

I totally support this. If shift+reload solves your problem maybe we could change the title of this ticket so it's about showing a version and build date in the settings page?

**Comment by silviot** [comment]
Superseded by #539 and #538
