### ISSUE TITLE
Feature: NewNoteButton

### ISSUE THREAD

**Issue by delasous** [librocco/librocco#46]
## Component: NewNoteButton
**Description:** 
- Button for adding new Notes.
- Two variants: 
  a. IN Button
    - Requires Warehouse name to be passed onClick, so that Note is added to correct Warehouse context
  b. OUT button
    - Add global OUT Note => does not require Warehouse context

**Mockup**: TODO: Standard component reference in Figma. Note: For now refer to green button in [this view](https://www.figma.com/file/yjspFXBKBIFJlC3wFv1FJL/The-Brocco?node-id=101%3A4320), and red button in [this view](https://www.figma.com/file/yjspFXBKBIFJlC3wFv1FJL/The-Brocco?node-id=101%3A5155) for variants.

### Requirements:
**Props:**
- variant/style: Enum of type
- Label: Button name. For IN Notes = Warehouse, for OUT Notes can = "New Note" | "Remove Books"
- onClick handler

**Styles:**
- IN = green
- OUT = red
 - OUT on UtilityNav has rounded corners on all sides

**Storybook**
- Default

**Functionality**
Adds a new Note

**Possible Enhancements**
Null

**Comment by ikusteu** [comment]
The way I see it, we can cover all scenarios with the following inputs (props):
- **type**:
  - in - green/white colours + right arrow
  - out - red/white colours + left arrow
- **fill**:
  - fill (default) - paints the button in colour (red/green), with white text and white icon (technically the fill of the icon is white, but the arrow is transparent, so it will have the same colour as background)
  - empty - doesn't paint the background (or paints it white) with text gray-600 and icon the appropriate type colour (red/green)
- **label**: 
  - just a regular string
  - this is simpler if we want to change the text contents of the button (or change the warehouse labels), we can do it in some central place, while the button needn't concern itself with which warehouse names are currently available
  - same ☝️ goes for i18n when we implement it
- **shape**:
  - square (default) - not necessarily square, but a symmetrical shape variant   
  - rounded-right - rounded only on the right hand side

The currently open PR #58 can go in as a first pass and the mentioned updates can be done as an enhancement

**Comment by ikusteu** [comment]
Additionally, the `onClick` in current implementation works as trivial `onClick` handler - no warehouse is passed in as the current spec. I actually think this is more natural as there is no confusion as to whether the warehouse name should be passed in, will it be `null` or undefined. Also, combined with the label logic being passed as a string, we can include the warehouse being used or not when consuming the component, like so:

When we want to pass warehouse name to open note function:

```typescript
const ParentInNoteComponent = ({ warehouseNames }) => {
  const openInNote = (warehouse: string) => {
    // do something with the warehouse name
  }

  return (
  <>
    {warehouseNames.map((wName) => (
        <NoteButton onClick={() => openInNote(warehouse)} {...someProps}>
          {wName}
        </NoteButton>
    )}
  </>)
}
```

When we don't want to pass warehouse name to open note function:

```typescript
const ParentOutNoteComponent = ({ warehouseNames }) => {
  const openOutNote = () => {
    // no warehouse name needed, open out note
  }

  return (
  <>
    {warehouseNames.map((wName) => (
        <NoteButton onClick={() => openOutNote()} {...someProps}>
          {wName}
        </NoteButton>
    )}
  </>)
}
```

**Comment by ikusteu** [comment]
When writing the spec for #68 I realised this component will be rendered interchangeably with `ListItem` so to keep prop interface similar, it would make sense to replace the **fill** prop (mentioned above ☝️) with:
- **active**?:boolean - truthy value would render the styles of `fill="empty"` and falsy would render `fill="fill"`
