### ISSUE TITLE
Namespace the different sections of the db

### ISSUE THREAD

**Issue by fadwamahmoud** [librocco/librocco#461]
During development, we're treating the orders db as an entity separate from the inventory. In production, that won't be the case and we need to namespace the inventory documents and orders documents, like so:

    v1/inventory/...rest-of-the-doc-path

    v1/orders/...rest-of-the-doc-path

[T-341](https://height.app/JUbb87uPQb/T-341)

**Comment by ikusteu** [comment]
This is based on the assumption of CouchDB as DBMS. With SQLite, it's completely unnecessary.
