### ISSUE TITLE
Feature: InNoteList

### ISSUE THREAD

**Issue by delasous** [librocco/librocco#47]
## Component: OutNoteList
**Description:** 
A purely functional component used as "controller" for `in-note` variant of #68 :
- List of active IN notes
  - Static label for each Note as a #45  which shows current Note with highlight. 
  - Note name updated in #66 should propagate here, and on edit should probably show a flash of colour to indicate it has changed.

**Mockup**: See #68 

#### Props:
- no props required as the component will get it's data from global state

#### Styles:
- should render #68 with `in-note` variant

#### Storybook:
- null

#### Functionality:
- should be hooked to global state:
  - router
  - local PouchDB instance
- should create items to pass to #68 (and render `FileNav` with appropriate variant):
  - the items should be warehouse names
  - subitems for each warehouse should be all in notes for given warehouse (pulled from PouchDB)
- should control the flash animation (on note update):
  - **lastUpdated** passed for each note subItem should be `0` at first, to not perform flash animation initially
  - each time a note is updated, should pass the value of `Date.now()` as **lastUpdated** to perform flash animation
  - see #45 
- onClick: 
  - clicking the warehouse name should open a form for new IN note with warehouse name (this state should be transferred using React router)  
  - clicking a note (subItem) should open the given note in #66 (this state should be transferred using React router)

#### Possible Enhancements:
- null

**Comment by ikusteu** [comment]
**Edit:** updated **functionality** and **elements** sections

**Comment by ikusteu** [comment]
Thinking about some challenges mentioned above, it feels that it would make sense to make this a "smart" component.
I like to think of atoms as "dumb" components:
- kinda like pure functions 👇  
- they do what they're told and render in a way they've been instructed to
- they should be stored in `ui` package

Components I consider "smart" are hooked into the app state and do their own thinking:
- hooked to state via redux, router, etc. 
- kinda like non-pure functions 👇 
- produce side effects
- are affected by the environment (global state)
- should be stored in `web` package (as they're utilising the app logic)

**Comment by ikusteu** [comment]
Updated the component to serve as a stateful "controller" for https://github.com/librocco/librocco/issues/68
