### ISSUE TITLE
Feature: OutNoteList

### ISSUE THREAD

**Issue by delasous** [librocco/librocco#48]
## Component: OutNoteList
**Description:** 
A purely functional component used as "controller" for `out-note` variant of #68 :
- List of active OUT notes
  - Static label for each Note as a #45  which shows current Note with highlight. 
  - Note name updated in #66 should propagate here, and on edit should probably show a flash of colour to indicate it has changed.

**Mockup**: See #68 

#### Props:
- no props required as the component will get it's data from global state

#### Styles:
- should render #68 with `out-note` variant

#### Storybook:
- null

#### Functionality:
- should be hooked to global state:
  - router
  - local PouchDB instance
- should create items to pass to #68 (and render `FileNav` with appropriate variant):
  - the only item should be "Out note" button
  - subitems should be all out notes (pulled from PouchDB)
- should control the flash animation (on note update):
  - **lastUpdated** passed for each note subItem should be `0` at first, to not perform flash animation initially
  - each time a note is updated, should pass the value of `Date.now()` as **lastUpdated** to perform flash animation
  - see #45 
- onClick: 
  - clicking the "New note" button should open a form for new out note (this state should be transferred using React router)
  - clicking a note (subItem) should open the given note in #66 (this state should be transferred using React router)

#### Possible Enhancements:
- null

**Comment by ikusteu** [comment]
Updated the component to serve as a stateful "controller" for #68
