### ISSUE TITLE
Feature: WarehouseList

### ISSUE THREAD

**Issue by delasous** [librocco/librocco#49]
## Component: WarehouseList
**Description:** 
A purely functional component used as "controller" for warehouse variant (`variant="default"`) of #68 :
- List of warehouses
  - Static label for each Warehouse as a #45  which shows current warehouse with highlight. 

**Mockup**: See #68 

#### Props:
- no props required as the component will get it's data from global state

#### Styles:
- should render #68 with `default` variant

#### Storybook:
- null

#### Functionality:
- should be hooked to global state:
  - router
  - local PouchDB instance
- should create items to pass to #68 (and render `FileNav` with appropriate variant):
  - the only item should be (disabled) warehouse button with appropriate icon
  - subitems should be al warehouses (pulled from PouchDB)
- onClick:
  - should open warehouse's stock on warehouse item click (this should be done using the router) 

#### Possible Enhancements:
- null

**Comment by ikusteu** [comment]
Closing this as it will be implemented directly in the page, using the already developed `SideNav` atoms. Could be reopened if wish to abstract it away in a component.
