### ISSUE TITLE
Optimise SQLite (SQLocal) performance

### ISSUE THREAD

**Issue by ikusteu** [librocco/librocco#516]
#512 introduces a SQLite implementation of the db interface. After observing performance of fully populated DB (using the current production DB as test data) we've pinpointed some bottlenecks (long running queries):
- note/warehouse list - **1700ms - 4800ms** -  the bottleneck seems to be the calculation of `totalBooks` when retrieving the list
- stock query (e.g. in search) - **1700ms - 9500ms** - again the retrieval of all entries and calculation of resulting quantities for each one
- publisher list query - **2000ms - 2100ms** - going through all rows of `books` table looking for distinct publishers
- note data query - **2000ms - 2100ms** - looking for a single note (by id), which is awkward since the id is the primary key of `notes` table

Potential fixes:
- add secondary indexes for tables based on critical queries
- stock can, potentially be cached (as we did for PouchDB impl, if memory serves right)
- perhaps limiting note data query to 1 result (there will be only one) might help with query performance
- if all else fails:
  - store `totalBooks` as part of note/warehouse entry and update on every change - sacrificing write performance for read
  - create a separate table for publishers, adding a new entry each time a new publisher is encountered - serving as a quick lookup table for queries

**Comment by ikusteu** [comment]
Current progress:
- note/warehouse list:
  - original: 1700ms - 4800ms
  - current: 800ms - 1600ms
- stock query (e.g. in search):
  - original 1700ms - 9500ms
  - current: 1700ms - 10000ms (not a regression -- non-determinism)
- publisher list query:
  - original: 2000ms - 2100ms
  - current: 800ms
- warehouse/note data query: 
  - original: 2000ms - 2100ms 
  - current: 500ms - 800ms

**Comment by silviot** [comment]
This is no longer relevant
