### ISSUE TITLE
Remove quantity from customer order line

### ISSUE THREAD

**Issue by fadwamahmoud** [librocco/librocco#592]
- Update the `createSupplierOrder` function to aggregate similar isbns to create a quantity field in the supplier_order_line
- supplier_order_line should have a quantity but it should not be editable. The price for a row will need to be calculated as SUM(supplier_order_line.quantity * book.price), 0) AS total_price

**Comment by delasous** [comment]
Does the `createSupplierOrder` function need to aggregate, or can we use the query that gets supplier order lines to aggregate. @silviot suggested that GROUP BY would be sufficient for this?

**Comment by silviot** [comment]
@delasous I think the aggregation should happen when we create the supplier order. A `GROUP BY isbn` together with a `SUM(quantity)` should do it.

**Comment by delasous** [comment]
Ok, makes sense. In my head the supplier order was behaving like a customer order in that it was never explicitly placed. But it is.
