### ISSUE TITLE
Feature: SideNav

### ISSUE THREAD

**Issue by ikusteu** [librocco/librocco#61]
## Component: SideNav

**Description**: The main navigation for top level pages/views. It should accept links and from those links render the buttons with specified icons, routing to the appropriate page/view. Should utilise already created `SideNavButton` with minor rewrites to wrap it into a React router`Link` component (and probably make it more opinionated). For more info (and app specific use case, see #32  

**Mockup**: [Figma](https://www.figma.com/file/yjspFXBKBIFJlC3wFv1FJL/The-Brocco?node-id=13%3A4083)

### Requirements

**Props**:
- Links (required: Array<LinkItem>): 
    - each entry should contain: 
        - href (string): pathname (without domain name)
        - Icon (SVGComponent): icon to render for the button link
   
**Styles**:
- On small screens this container should be hidden in favour of a MobileMenu (which is collapsable from top UtilityBar), check breakpoint at which the menu should be hidden (I think we can use one of Tailwind's default breakpoints)

**Storybook**:
- Default 

**Functionality (should be tested):**

- should link to appropriate pathname  

**Possible Enhancements**

- null

### Progress:

This unit of work includes features described in #32 and #34 

**TODO:**

- [ ] Create a styled component (plus storybook)
- [ ] Rewrite `SideNavButton` into `SideNavLink` to be used for this specific use case

**Comment by delasous** [comment]
> Logo (required: SVGComponent): Logo to be shown at the top of the nav (@delasous correct me here if you've imagined it without the logo or some other way)

I think we should put a logo here but for now, in the absence of our own design, it may be simpler just to extend the bar right to the top of the screen?

**Comment by ikusteu** [comment]
Stale, mockup has changed
