### ISSUE TITLE
Feature: Typography

### ISSUE THREAD

**Issue by ikusteu** [librocco/librocco#62]
## Component: Typography

**Description:** An opinionated set of typefaces (or a single typeface) coupled with font sizes, font weights, color, etc. Should represent the most (if not all) of the text we'll use across the app (buttons and some very specific cases can be omitted)

**Mockup:** No mockup yet, @delasous could you provide something in Figma regarding the matter. It wouldn't need to be a large set of variants (some made up and not used yet), but rather the grouping of [type](https://www.figma.com/file/yjspFXBKBIFJlC3wFv1FJL/The-Brocco?node-id=13%3A3573) with colors/font-weights used in the app (the fully mocked views). Additionally, if you come up with new variants while mocking up additional views, the component can easily be extended to include new ones.  

#### Props (should extend React.HTMLAttributes<HTMLElement>):
- variant (required: string enum):
  - heading
  - text
- size (optional: string enum): 
  - xs
  - sm
  - base (default)
  - lg
  - xl
  - (... could be extended to feature xxs, 2xl, 3xl, etc...)
- lineHeight (optional: string enum):
  - tight (default)
  - relaxed
  - loose 
- fontWeight (optional: string enum):
  - regular (default)
  - medium
  - semibold
  - bold
  - extrabold
- as (optional: keyof JSX.IntrinsicElements)
  - default: `span`

#### Styles:

Each variant would entail:
- color (the way I see it, heading would, maybe, be gray-900 and text gray-500) - could be overridden by `className`
- different way of understanding `size` e.g. For heading `base` could be `text-lg` while for text `base` could be `text-md` (this is purely hypothetical)
- lineHeight would be different depending on font size: each font size would have `tight`, `relaxed`, `loose` values for `leading-{line-height}`

#### Storybook (stories):

- Sizes
- Weights
- Colors

#### Functionality (should be tested):

- null

### Possible enhancements:

- null

**Comment by ikusteu** [comment]
@delasous the implementation described in the spec is something I've picked up from past experience and makes most sense to me. However, this really depends on design choices, namely the amount of text variants you plan on using in the mockup. I'll leave that point to you (maybe to consult with Alex) and then we can talk on exact implementation as I understand this might be an overkill if we'll be using only 3, 4 variants of text across the entire app.

**Comment by delasous** [comment]
Given the small range of text variants within the app, I would suggest we create a constrained list of opinionated styles that includes in one reference the size, font-weight, line-height etc, and select each variant with a single prop key

**Comment by ikusteu** [comment]
Agreed, could you just isolate all of them in one place in Figma, so that there's a single source of truth for whomever will be picking this up.
