### ISSUE TITLE
Feature: PageTemplate

### ISSUE THREAD

**Issue by ikusteu** [librocco/librocco#67]
## Component: InventoryPage

_This would be a template for page styling, but I think it would make more sense to call is simply InventoryPage`

**Description:** This component would be used as presentational template for a page component. To clarify on @delasous comment about seeing how this fits into svelte's layout practices:
I'm **not** suggesting we make this a `+layout.svelte` type of component. This component would merely be a complex (stateless) style container. Example usage:
```svelte
<InventoryPage>

<svelte:fragment name="sidebar">
  <SideBarComponent(s) />
</svelte:fragment>

<svelte:fragment name="table-section">
  {#each tableRows as row}
    <TableRowComponent {...row} />
  {/each}
</svelte:fragment>

</InventoryPage>
```

There are certain points why I feel this makes sense:
- it would abstract away the positioning of main content containers on the page
- by abstracting away the container css logic, we avoid code redundancy per page basis
- when mobile version mockup is created, it would be easier to apply automatic repositioning of said containers

#### Elements (containers):

Thanks to Svelte's extremely convenient way of rendering elements passed as named slots (`<Container><slot name="section-1"/></Container>`), the implementation becomes trivial and requires minimum to no props (compared to a would-be React implementation)

- Header:
  - The entire `Header` component could get passed into this slot:
    - that way we can reuse the header component, but have the designated space where it would be rendered
- Sidebar:
  - shown on the leftmost side bar
  - should span the entire height of the page and scroll on `overflow-y`
  - `overflow-x` should be hidden (if an element overflows, we could show the ellipsis)
- Table heading: 
  - would show title, search bar, action buttons (depending on the page/view)
- Table section:
  - shows table rows for a view (stock, transactions)
  - even though number of table entries per page would be limited, we might want to enable overflow-y-scroll
- Table Footer:
  - for now it seems it will be the same across views (show number of items shown, number of total items and pagination)
  - even though it's the same across pages it still makes sense to pass it as a named slot (rather than abstracting it away in `Page` template to allow for the caller (the `+page.svelte`) direct control over the pagination functionality

### Possible enhancements:
- Small screen: this really depends on the future small screen mockup: the existing containers could be extended to simply rearrange on smaller screens, or extend the props and have sm version of each container at which point the content in large screen containers would be hidden and sm content shown instead

**Comment by delasous** [comment]
Looks great and totally agree! Only additional point I'd throw into the Possible Enhancements corner would be to have SideBar slot content collapsible (to the left). This could help small-med screen situations without too much effort.
