### ISSUE TITLE
Set up YAML generation for workflow files

### ISSUE THREAD

**Issue by ikusteu** [librocco/librocco#73]
Silvio mentioned some yaml generator to help us write our workflows with reduced redundancy (and have single source of truth) for recurring workflow steps. 

@silviot please provide additional information and the tool to use for this work

**Comment by silviot** [comment]
I'm working on a `ytt` based approach to github actions yml files generation.
https://carvel.dev/ytt/#example:example-load
I started with `EisBuk`: https://github.com/eisbuk/EisBuk/tree/feature/actions-ytt

**Comment by ikusteu** [comment]
Is this finished ?? @silviot @fadwamahmoud 
I feel there's room for improvement/reduced redundancy (as I've mentioned in #88 ), but I feel this, as a first pass is solved, can I close this or is there some unmerged work on the matter?
